version: '3.9'

x-logging: &logging
  logging:
    driver: 'json-file'
    options:
      max-size: '400k'
      max-file: '20'

services:
  cardano-node:
    volumes:
      - ./config/network/${NETWORK:-mainnet}/cardano-node:/config
      - ./config/network/${NETWORK:-mainnet}/genesis:/genesis

  ogmios:
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config

  cardano-db-sync:
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config

  cardano-smash:
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config

  cardano-submit-api:
    volumes:
      - ./config/network/${NETWORK:-mainnet}:/config

  blockfrost-worker:
    <<: *logging
    build:
      context: ../../
      target: blockfrost-worker
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CACHE_TTL=${CACHE_TTL:-240}
      - CREATE_SCHEMA=${CREATE_SCHEMA:-true}
      - DROP_SCHEMA=${DROP_SCHEMA:-false}
      - LOGGER_MIN_SEVERITY=${LOGGER_MIN_SEVERITY:-info}
      - NETWORK=${NETWORK:-mainnet}
      - SCAN_INTERVAL=${SCAN_INTERVAL:-60}
    ports:
      - ${API_PORT:-4001}:3000
    restart: on-failure
    secrets:
      - blockfrost_key
      - postgres_db_db_sync
      - postgres_password
      - postgres_user

  handle-projector:
    environment:
      HANDLE_POLICY_IDS: $HANDLE_POLICY_IDS

  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data

  provider-server:
    environment:
      HANDLE_POLICY_IDS: $HANDLE_POLICY_IDS

  handle-provider-server:
    environment:
      HANDLE_POLICY_IDS: $HANDLE_POLICY_IDS

secrets:
  blockfrost_key:
    file: ./blockfrost-keys/${NETWORK:-mainnet}.key

volumes:
  postgres-data:
